# Generated by Django 5.2.18 on 2026-10-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seed_url', models.URLField(help_text='Start page; the crawler stays on this host.', max_length=500)),
                ('path_prefix', models.CharField(blank=True, help_text='Only crawl paths starting with this.', max_length=200)),
                ('max_pages', models.PositiveIntegerField(default=100)),
                ('delay_seconds', models.FloatField(default=1.0, help_text='Minimum gap between requests (Crawl-delay may raise it).')),
                ('use_sitemap', models.BooleanField(default=True)),
                ('rebuild_index', models.BooleanField(default=True, help_text='Rebuild the search index when the crawl finishes.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_indexed', models.PositiveIntegerField(default=0)),
                ('pages_skipped', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('mode', models.CharField(max_length=10)),
                ('results', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('indexed', 'Indexed'), ('blocked_by_robots', 'Blocked by robots.txt'), ('not_html', 'Not HTML'), ('http_error', 'HTTP error'), ('duplicate', 'Duplicate content'), ('noindex', 'noindex'), ('link_hub', 'Mostly links (followed, not indexed)'), ('error', 'Network error')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='search.crawljob')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
    ]
